name: pull

on:
  push:
    branches:
      - master

jobs:
  build-images:
    name: Pull code from master to dev.specavto.info
    runs-on: ubuntu-latest

    steps:
      - name: pull newest code to dev.specavto.info from master
        env:
          UPDATER_KEY: ${{ secrets.UPDATER_KEY }}
        run: curl https://hooks.dev.specavto.info/update/pull-code/${UPDATER_KEY}
